using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HRMS.Entity;
using HRMS.DAL;
using HRMS.Exceptions;
using System.Data;
using System.Data.SqlClient;
using System.Text.RegularExpressions;

namespace HRMS.BL
{
    /// <summary>
    /// CivilStatus ID :161611
    /// CivilStatus Name : Mansih
    /// Description : Validate Level details  and call Level  operations methods in DAL
    /// Date of Creation : 01/11/2018
    /// </summary>
    /// 
    public class Level_BL
    {
        //Validation of Details
        public static bool ValidatLevel(Level newLevel)
        {

            bool isValidLevel = true;
            StringBuilder sbError = new StringBuilder();
            try
            {
                if (newLevel.LevelDescription == string.Empty)
                {
                    isValidLevel = false;
                    sbError.Append("Please Enter Level Description");
                }



                if (!isValidLevel)
                    throw new HRMSException(sbError.ToString());
            }
            catch (HRMSException ex)
            {
                throw ex;
            }

            return isValidLevel;
        }

        //Calling Add Level
        public static int AddLevel_BL(Level newLevel)
        {
            int rowsAffected = 0;
            try
            {
                if (ValidatLevel(newLevel))
                {
                    rowsAffected = Level_DAL.AddLevel(newLevel);
                }


            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Calling Update Level
        public static int UpdateLevel_BL(Level newLevel)
        {
            int rowsAffected = 0;
            try
            {
                if (ValidatLevel(newLevel))
                {
                    rowsAffected = Level_DAL.UpdateLevel(newLevel);
                }


            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Get Autogenerated ID
        public static int GetAutogeneratedLevelID_BL()
        {
            int Levelid = 0;
            try
            {


                Levelid = Level_DAL.GetAutoGeneratedLevelId();



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return Levelid;
        }

        //Delete Level
        public static int DeleteLevel_BL(int Levelid)
        {
            int rowsAffected = 0;
            try
            {


                rowsAffected = Level_DAL.DeleteLevel(Levelid);



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Search Level By Id
        public static DataTable SearchLevelById_BL(int Levelid)
        {
            DataTable level = null;
            try
            {


                level = Level_DAL.SearchLevelById(Levelid);



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return level;
        }

        //Dispaly All Level
        public static DataTable DisplayLevel_BL()
        {
            DataTable level = null;
            try
            {


                level = Level_DAL.DisplayAllLevels();



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return level;
        }
    }
}
