using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HRMS.Entity;
using HRMS.DAL;
using HRMS.Exceptions;
using System.Data;
using System.Data.SqlClient;
using System.Text.RegularExpressions;

namespace HRMS.BL
{
    /// <summary>
    /// CivilStatus ID :161611
    /// CivilStatus Name : Manish Rahangdale
    /// Description : Validate Skill details  and call Skill  operations methods in DAL
    /// Date of Creation : 01/11/2018
    /// </summary>
    /// 
    public class Skill_BL
    {
        //Validation of Details
        public static bool ValidatSkill(Skill newSkill)
        {

            bool isValidSkill = true;
            StringBuilder sbError = new StringBuilder();
            try
            {
                if (newSkill.SkillName == string.Empty)
                {
                    isValidSkill = false;
                    sbError.Append("Please Enter Skill Name");
                }
                else if (!Regex.IsMatch(newSkill.SkillName, "[A-Z][a-z]{2,}"))
                {
                    sbError.Append("Skill Name should start with Capital Alphabet, it should have minimum 3 characters and only alphabets\n");
                    isValidSkill = false;
                }
                if (newSkill.SkillDescription == string.Empty)
                {
                    isValidSkill = false;
                    sbError.Append("Please Enter Skill Description");
                }







                if (!isValidSkill)
                    throw new HRMSException(sbError.ToString());
            }
            catch (HRMSException ex)
            {
                throw ex;
            }

            return isValidSkill;
        }

        //Calling Add Skill
        public static int AddSkill_BL(Skill newSkill)
        {
            int rowsAffected = 0;
            try
            {
                if (ValidatSkill(newSkill))
                {
                    rowsAffected = Skill_DAL.AddSkill(newSkill);
                }


            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Calling Update Skill
        public static int UpdateSkill_BL(Skill newSkill)
        {
            int rowsAffected = 0;
            try
            {
                if (ValidatSkill(newSkill))
                {
                    rowsAffected = Skill_DAL.UpdateSkill(newSkill);
                }


            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Get Autogenerated ID
        public static int GetAutogeneratedSkillID_BL()
        {
            int Skillid = 0;
            try
            {


                Skillid = Skill_DAL.GetAutoGeneratedSkillId();



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return Skillid;
        }

        //Delete Skill
        public static int DeleteSkill_BL(int Skillid)
        {
            int rowsAffected = 0;
            try
            {


                rowsAffected = Skill_DAL.DeleteSkill(Skillid);



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Search Skill By Id
        public static DataTable SearchSkillById_BL(int Skillid)
        {
            DataTable skill = null;
            try
            {


                skill = Skill_DAL.SearchSkillById(Skillid);



            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return skill;
        }

        //Dispaly All Skill
        public static DataTable DisplaySkill_BL()
        {
            DataTable skill = null;
            try
            {

                skill = Skill_DAL.DisplayAllSkills();


            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return skill;
        }

        //Dispaly All Skill
        public static DataTable LoadCatSkill_BL()
        {
            DataTable cat = null;
            try
            {

                cat = Skill_DAL.LoadCategory();


            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return cat;
        }
    }
}
