using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HRMS.Entity;
using HRMS.DAL;
using HRMS.Exceptions;
using System.Data;
using System.Data.SqlClient;
using System.Text.RegularExpressions;

namespace HRMS.BL
{
    public class Speciality_BL
    {
        //Validation of Details
        public static bool ValidatSpec(Speciality newSpec)
        {

            bool isValidSpec = true;
            StringBuilder sbError = new StringBuilder();
            try
            {
                if (newSpec.SpecialityName == string.Empty)
                {
                    isValidSpec = false;
                    sbError.Append("Please Enter Speciality Name");
                }



                if (!isValidSpec)
                    throw new HRMSException(sbError.ToString());
            }
            catch (HRMSException ex)
            {
                throw ex;
            }

            return isValidSpec;
        }

        //Calling Add Speciality
        public static int AddSpeciality_BL(Speciality newSpec)
        {
            int rowsAffected = 0;
            try
            {
                if (ValidatSpec(newSpec))
                {
                    rowsAffected = Speciality_DAL.AddSpeciality(newSpec);
                }
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Calling Update Speciality
        public static int UpdateSpeciality_BL(Speciality newSpec)
        {
            int rowsAffected = 0;
            try
            {
                if (ValidatSpec(newSpec))
                {
                    rowsAffected = Speciality_DAL.UpdateSpec(newSpec);
                }
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Get Autogenerated ID
        public static int GetAutogeneratedSpecialityID_BL()
        {
            int Specialityid = 0;
            try
            {
                Specialityid = Speciality_DAL.GetAutoGeneratedSpecId();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return Specialityid;
        }

        //Delete Speciality
        public static int DeleteSpeciality_BL(int Specialityid)
        {
            int rowsAffected = 0;
            try
            {
                rowsAffected = Speciality_DAL.DeleteSpec(Specialityid);
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Search Speciality By Id
        public static DataTable SearchSpecialityById_BL(int Specialityid)
        {
            DataTable Speciality = null;
            try
            {
                Speciality = Speciality_DAL.SearchSpecById(Specialityid);
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return Speciality;
        }

        //Display All Speciality
        public static DataTable DisplaySpeciality_BL()
        {
            DataTable Speciality = null;
            try
            {
                Speciality = Speciality_DAL.DisplayAllSpeciality();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (HRMSException ex)
            {
                throw ex;
            }
            return Speciality;
        }
    }
}
