using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HRMS.Entity;
using System.Data;
using System.Data.SqlClient;

namespace HRMS.DAL
{
    /// <summary>
    /// Employee ID :161585
    /// Employee Name : Viraj Dere
    /// Description : Handles Civil_Status Specific operations
    /// Date of Creation : 10/23/2018
    /// </summary>
    public class CivilStatus_DAL
    {
        //Function to get autogenerated CivilStat Id
        public static int GetAutoGeneratedCivilStatusId()
        {
            int newCivilStatId;
            try
            {
                SqlConnection connObj = new SqlConnection(@"Data Source=ndamssql\sqlilearn;Initial Catalog=Sep19CHN;User ID=sqluser;Password=sqluser");
                SqlCommand cmdObj = new SqlCommand("select IDENT_CURRENT('Group4.Civil_Status')+ident_incr('Group4.Civil_Status')", connObj);
                connObj.Open();
                object objResult = cmdObj.ExecuteScalar();
                newCivilStatId = Convert.ToInt32(objResult);
                connObj.Close();// return single data - obj
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return newCivilStatId;

        }

        //Method to Add CivilStat to Database
        public static int AddCivilStat(CivilStatus newCivilStat)
        {
            int rowsAffected = 0;
            try
            {
                //Creating command object
                SqlCommand civilStatCommand = DataConnections.GenerateCommand();

                //Assigning command text
                civilStatCommand.CommandText = "Group4.usp_AddCivilStatus";

                //Adding parameters to command
                civilStatCommand.Parameters.AddWithValue("@Status_Description", newCivilStat.StatusDescription);
                

                //Executing command
                civilStatCommand.Connection.Open();
                rowsAffected = civilStatCommand.ExecuteNonQuery();
                civilStatCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Method to Delete CivilStat From Database
        public static int DeleteCivilStat(int civilStatId)
        {
            int rowsAffected = 0;
            try
            {
                //Creating command object
                SqlCommand civilStatCommand = DataConnections.GenerateCommand();
                //Assigning command text

                civilStatCommand.CommandText = "Group4.usp_DeleteCivilStatus";
                civilStatCommand.Parameters.AddWithValue("@Status_Id", civilStatId);

                civilStatCommand.Connection.Open();
                rowsAffected = civilStatCommand.ExecuteNonQuery();
                civilStatCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return rowsAffected;

        }

        //Method to Modify CivilStat From Database
        public static int UpdateCivilStat(CivilStatus newCivilStat)
        {
            int rowsAffected = 0;
            try
            {
                //Creating command object
                SqlCommand civilStatCommand = DataConnections.GenerateCommand();
                //Assigning command text

                civilStatCommand.CommandText = "Group4.usp_UpdateCivilStatus";
                civilStatCommand.Parameters.AddWithValue("@Status_Description", newCivilStat.StatusDescription);

                civilStatCommand.Connection.Open();
                rowsAffected = civilStatCommand.ExecuteNonQuery();
                civilStatCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Method to Display CivilStat From Database
        public static DataTable DisplayAllCivilStats()
        {
            DataTable dtCivilStat;
            SqlDataReader CivilStatReader = null;
            try
            {
                //Creating command object
                SqlCommand civilStatCommand = DataConnections.GenerateCommand();

                dtCivilStat = new DataTable();
                civilStatCommand.CommandText = "Group4.usp_DisplayAllCivilStatus";
                civilStatCommand.Connection.Open();
                CivilStatReader = civilStatCommand.ExecuteReader();
                if (CivilStatReader.HasRows)
                {
                    dtCivilStat.Load(CivilStatReader);
                }
                CivilStatReader.Close();
                civilStatCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return dtCivilStat;
        }

        //Method to Search CivilStat From Database
        public static DataTable SearchCivilStatById(int CivilStatId)
        {
            DataTable dtCivilStat;
            SqlDataReader CivilStatReader = null;
            try
            {
                //Creating command object
                SqlCommand civilStatCommand = DataConnections.GenerateCommand();

                dtCivilStat = new DataTable(/*int CivilStatId*/);
                civilStatCommand.CommandText = "Group4.usp_SearchCivilStatus";
                civilStatCommand.Parameters.AddWithValue("@Status_Id", CivilStatId);
                civilStatCommand.Connection.Open();
                CivilStatReader = civilStatCommand.ExecuteReader();
                if (CivilStatReader.HasRows)
                {
                    dtCivilStat.Load(CivilStatReader);
                }
                CivilStatReader.Close();
                civilStatCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return dtCivilStat;
        }
    }
}
