using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HRMS.Entity;
using System.Data;


namespace HRMS.DAL
{
    /// <summary>
    /// Employee ID :161585
    /// Employee Name : Viraj Dere
    /// Description : Handles Employee-Project Specific operations
    /// Date of Creation : 10/23/2018
    /// </summary>
    public class Project_DAL
    {
        //Function to get autogenerated Project Id
        public static int GetAutoGeneratedProjectId()
        {
            int newProjectId;
            try
            {
                SqlConnection connObj = new SqlConnection(@"Data Source=ndamssql\sqlilearn;Initial Catalog=Sep19CHN;User ID=sqluser;Password=sqluser");
                SqlCommand cmdObj = new SqlCommand("select IDENT_CURRENT('Group4.Project')+ident_incr('Group4.Project')", connObj);
                connObj.Open();
                object objResult = cmdObj.ExecuteScalar();
                newProjectId = Convert.ToInt32(objResult);
                connObj.Close();// return single data - obj
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return newProjectId;

        }

        //Method to Add Project to Database
        public static int AddProject(Project newProj)
        {
            int rowsAffected = 0;
            try
            {
                //Creating command object
                SqlCommand projCommand = DataConnections.GenerateCommand();

                //Assigning command text
                projCommand.CommandText = "Group4.usp_AddProject";

                //Adding parameters to command
                projCommand.Parameters.AddWithValue("@Project_Name", newProj.ProjectName);
                projCommand.Parameters.AddWithValue("@Project_Description", newProj.ProjectDescription);
                projCommand.Parameters.AddWithValue("@Project_Client", newProj.ProjectClient);
                projCommand.Parameters.AddWithValue("@Project_Start_Date", newProj.ProjectStartDate);
                projCommand.Parameters.AddWithValue("@Project_End_Date", newProj.ProjectEndDate);
                
                //Executing command
                projCommand.Connection.Open();
                rowsAffected = projCommand.ExecuteNonQuery();
                projCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Method to Delete Project From Database
        public static int DeleteProject(int projId)
        {
            int rowsAffected = 0;
            try
            {
                //Creating command object
                SqlCommand projCommand = DataConnections.GenerateCommand();
                //Assigning command text

                projCommand.CommandText = "Group4.usp_DeleteProjects";
                projCommand.Parameters.AddWithValue("@Project_Id", projId);

                projCommand.Connection.Open();
                rowsAffected = projCommand.ExecuteNonQuery();
                projCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return rowsAffected;

        }

        //Method to Modify Project From Database
        public static int UpdateProject(Project newProj)
        {
            int rowsAffected = 0;
            try
            {
                //Creating command object
                SqlCommand projCommand = DataConnections.GenerateCommand();
                //Assigning command text

                projCommand.CommandText = "Group4.usp_UpdateProject";
                projCommand.Parameters.AddWithValue("@Project_Id",newProj.ProjectId);
                projCommand.Parameters.AddWithValue("@Project_Name", newProj.ProjectName);
                projCommand.Parameters.AddWithValue("@Project_Description", newProj.ProjectDescription);
                projCommand.Parameters.AddWithValue("@Project_Client", newProj.ProjectClient);
                projCommand.Parameters.AddWithValue("@Project_Start_Date", newProj.ProjectStartDate);
                projCommand.Parameters.AddWithValue("@Project_End_Date", newProj.ProjectEndDate);
                projCommand.Connection.Open();
                rowsAffected = projCommand.ExecuteNonQuery();
                projCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return rowsAffected;
        }

        //Method to Display Project From Database
        public static DataTable DisplayAllProjects()
        {
            DataTable dtProj;
            SqlDataReader projReader = null;
            try
            {
                //Creating command object
                SqlCommand projCommand = DataConnections.GenerateCommand();

                dtProj = new DataTable();
                projCommand.CommandText = "Group4.usp_DisplayAllProjects";
                projCommand.Connection.Open();
                projReader = projCommand.ExecuteReader();
                if (projReader.HasRows)
                {
                    dtProj.Load(projReader);
                }
                projReader.Close();
                projCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return dtProj;
        }

        //Method to Search Project From Database
        public static DataTable SearchProjectById(int projId)
        {
            DataTable dtProj;
            SqlDataReader projReader = null;
            try
            {
                //Creating command object
                SqlCommand projCommand = DataConnections.GenerateCommand();

                dtProj = new DataTable(/*int projId*/);
                projCommand.CommandText = "Group4.usp_SearchProject";
                projCommand.Parameters.AddWithValue("@Project_Id", projId);
                projCommand.Connection.Open();
                projReader = projCommand.ExecuteReader();
                if (projReader.HasRows)
                {
                    dtProj.Load(projReader);
                }
                projReader.Close();
                projCommand.Connection.Close();
            }
            catch (SqlException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return dtProj;
        }
    }
}
